apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo-runners
---
apiVersion: v1
kind: Namespace
metadata:
  name: omni
---
apiVersion: v1
kind: Namespace
metadata:
  name: renovate
---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
