---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAP8apZPUlPAH+rBv6cmu5iUKT64+6VFJUq16gyiI/rLKBIDrCqJ4zQRD6qOY8VVdcEVR/AYLc21nmHLZ705SybBZUh8TcvkyEmWZIscjj6W2zDR6X7TVT6ckjgPoC7pJx+9vYfyi1umXX2mx2EiYf52e/fnoBI8RGSpbnTCpgPTgiBNVpGxqo+ebCjZN/pjZrV9g3aUcyhR/11lxSvMtRnDIsncGD240vqsiimAv3gIq9RTRZ4Yx1StsbzUJWyWhBs0flEsDL4bKlGjflMrHm6QJxihFCCDnUhVt6B1QqTGym2q3E6kezGKlR9B3LiuRAaXSfIqy7l0RvbYF8ZrEBRTKVKpTcX/9WkXMNTGnFTYMks+gY29ATEBPXv+JETZ89iSSc+UjeEWKpMIcOOz7xhnECexD8m/u14JAIIF+RyoWpZajioFU31gphXSQjnTmmpfZld5pybSI7exTyT1wVvOGNEQaCsMGOAk/37ghdfNdxP27Mc5AGFShHO++s8fluqkNK+HpbPXGRiXSOUlss2LDy836DqaZy/hbi4pKzVki/iks+Z33+jbKQAIyAfd9KI5aw5acFsjkxBUtFAynYyaWW6qSaHZWLxb1gIFwY5kzqpGkxcQU1sJBIB85eJBpOITFktBqsy7jrJevXcUpZ40ePy12rQm3B6rqrJVmtKmUE8wADvfIder64bCVxPEuCbVf4sK5NsI29sGi/G/UdX1cYJfs0xZxnpogtXPJ+i3gXPWhVAooV4iBXXB7WgluVysovhsQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
