---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAhTf6XEBI+CnViWM1YulBA7ZmPE4I9YTZOiHcNdVkZozER+qQZM87IyJt1Himj2lKWqyMSGEh7t5TDsV3bAMmvPVXmiqx+95AWCSnZcEeO1UMThb3ImWPNYAoQdtUJ6mAQOen6aFDc4rC11No/NXjtPqEi+zk25E8AyI3IVfgUoldXcK6xwh+jE1sV0Mj7BFievhuFDHkAY1Abh4yRI90F4YRRIxVyESaAd5IJiWTfit47RVBScZgJmRIFO3XXYeIgjxxpd0J64LKdrDapqDqI86UPdOh9vnh3EGSHM9NpEfS8130mpidKmJ/ZMXE9vXBamZbyFdKaZaKhAhHq4WY9sveFvdYEI9pgKfzjUnBulin2a60fB8jHgRrTMNo+cJ78/2xV786lB3Jboo+6d71IPl6OLEgWWH1tvLgOPWkYGJofiA8CrYlksWrDZRBO7JX0g/toFAbU89AmGNLcpZvNVQOtZ3KEJjGb9e8MAFGsPGkXqU8TSc1En4jhNtSI8lZ+X5PGciA0U/VHpWUxU9kGhKfR5mcpNe8FcPGF9SD+Niiy1zP+VGBQInmBc4I3t4d/z7vwf0I5qaIkc1NIZ0iI14dPIZIr+e+UbJQkXUE+b1rjJn1zY2ejiXMR7UORJBEngc/NpBPO9QaBxzmuYObxJicOE7Mi4OTB4ipRhtWcnd1q1KFHmFkWnEhRgNFgIDOqTZwGuSRwYP1H/NLG8UJmPG9uguJChgw/yj0jIvh6MEJvIwDLtLQGSaNXKjxIes6cIoRZZTJ2cebDQJ8HTw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
