---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCEeLyji0mErfCcrSr8mguO7EhdASfb/mLt7yM/CPbZbskiHGsBnfXl+Qu3QT4wlPeiQv3YVYf4AUHll6c3BBiC20zg5HF3EP9NEew2R9ivzXZu1LYZiFNud/QEnmPGULPwX4+++VLZfbFknSmuskSpBHiRrpEuctU0DyDqGLQG3vflqizi442iVdqEtqiUCJzV9HQtPfzLDuux0NaNUdAaOc7LYe+pA2E4Wj02+Int2uLQ9O8LMs1djYr1zb7E3kbCEbR5CQLWtfgrwiRcwyNYwYCKuSCxDqrPX3vCR7s/Cecm3W/1s1c/19TvCo2a0VFfQtoMCbsEnL3BWo0hJQc8ptcABNY/ypuda+AFG+BZ3cn5QJKxCdFcOT8Bhefk48x8aY9rv0BowUw465IQu5XE8UB//GHzxhBwkUSQmTvWGjl0IMNbhUphADoWxKqbJJgny2Q4omlfEQaeJtrrI46QpabfChcgyjNo68BbhE2AKkxZHMyUqkfAaHRI72sRsYhuW47Xks6h/w/fykV95KDW5kNRpuOae0wx2LwYHTyFm/c9PVRLkHj9PnOsmNPnnlqh/hN7rp/vRlU/qqvDygVq9aaUXypFy1Ntv+l0l9FOZd7+epiWeG6THHQ6uEHUquZhyCsDpFNelPXuJyt90IcyYe/6X3eEMCXJVlPgSyIkt1Wt6O6JoYhK5duASFE4EQ7wpIEeqZaZ3UpkC63Iz1eyYeBVbXRHgYRV8lmXsLxfRKv2+0gL9MYKZ0RNisgjAZQ+DapVYalPCjUF8K5sGA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
